"""Add release_year to films

Revision ID: 02806a65e924
Revises: 
Create Date: 2025-01-03 23:29:30.418489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02806a65e924'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('films', schema=None) as batch_op:
        batch_op.add_column(sa.Column('release_year', sa.Integer(), nullable=False))
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.drop_column('release_date')
        batch_op.drop_column('poster')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('films', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poster', sa.VARCHAR(length=80), nullable=False))
        batch_op.add_column(sa.Column('release_date', sa.DATE(), nullable=False))
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('release_year')

    # ### end Alembic commands ###
